# Generated by Django 5.0.6 on 2024-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.SmallIntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_phone', models.CharField(max_length=10, unique=True)),
                ('patient_email', models.EmailField(max_length=100, unique=True)),
                ('patient_city', models.CharField(max_length=50)),
                ('patient_symptoms', models.CharField(max_length=1000)),
                ('registeration_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
