# Generated by Django 5.0.6 on 2024-05-17 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='patient_name',
            new_name='patient_father_name',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='patient_phone',
            new_name='patient_mobile',
        ),
        migrations.AddField(
            model_name='patients',
            name='patient_full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
