# Generated by Django 5.0.6 on 2024-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_rename_patient_name_patients_patient_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_image',
            field=models.ImageField(null=True, upload_to='patient image/'),
        ),
    ]
