# Generated by Django 5.0.6 on 2024-06-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_alter_patients_patient_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_designation', models.CharField(max_length=20)),
                ('staff_email', models.EmailField(max_length=100, unique=True)),
                ('staff_mobile', models.CharField(max_length=10, unique=True)),
                ('staff_password', models.CharField(max_length=18)),
            ],
        ),
    ]
