# Generated by Django 5.0.6 on 2024-06-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_password',
            field=models.CharField(editable=False, max_length=18),
        ),
    ]
